### ISSUE TITLE
Event names in documentation are incorrect

### ISSUE THREAD

**Issue by antoligy** [Financial-Times/o-squishy-list#13]
Hi, I wasn't sure if this was my misinterpreting the documentation or whether or not this was really the case:
Consistently event-names are referred to with the prefix oPrioritisedContentFilter, however the events which are fired have the oSquishyList prefix (and appear to be hardcoded to do so).  Is this correct, or is the documentation page wrong?

Cheers!
Alex.

**Comment by AlbertoElias** [comment]
Fixed in #14 Thanks for reporting!

**Comment by antoligy** [comment]
Cheers!
