### ISSUE TITLE
update to documentation

### ISSUE THREAD

**Issue by eddichen** [Financial-Times/o-squishy-list#19]
can the documentation be updated to mention that in your styling you need to include 
```[aria-hidden="true"] {
    display: none;
}```
to see the items appear/disappear

also it's not clear how to get this to work via the build service. I resorted to using the manual process.

**Comment by alicebartlett** [comment]
Yep, let me just add this for you. Sorry it's taken me 20(!) days to get to this. Feel free to just open PRs for this kind of thing in the future.

**Comment by alicebartlett** [comment]
I've looked into your second point, which is that autoinit doesn't work for this module. That's a bug! Or maybe a "feature"?

Anyway, I've opened another issue for that (https://github.com/Financial-Times/o-squishy-list/issues/21). How highly we prioritise that work depends on if you still want to use it. Let us know in a comment.

**Comment by eddichen** [comment]
This isn't a high priority as i'm using the manual service for this module and it's working fine.
