### ISSUE TITLE
Use o-viewport to listen to window resize

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-squishy-list#4]

**Comment by onishiweb** [comment]
Is this still an issue?

**Comment by wheresrhys** [comment]
Yes, because oViewport takes care of throttling centrally and it'd be easy to implement
No, because o-squishy list isn't widely used 

¯\_(ツ)_/¯

**Comment by onishiweb** [comment]
ok, we'll keep it open, but low priority

**Comment by gvonkoss** [comment]
This is a deprecation candidate, but we can reopen this issue if we decide to keep the component.
