### ISSUE TITLE
Clarify browser support

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/o-squishy-list#6]
This component does not indicate what browsers it has been tested on, making it hard for products to make a decision to whether to use it. If you've not done so, please can you test it and document where this code will run.

**Comment by onishiweb** [comment]
The component supports core and enhanced experiences so it should conform to the standard browser support list (discussed in the spec: http://origami.ft.com/docs/developer-guide/using-modules/#core-vs-enhanced-experience)
